//Flat variant of the ElectricalComponent SimpleCircuit in the eletrical component package
model SimpleCircuit
  Real AC_i;
  Real AC_n_v;
  Real AC_p_v;
  Real AC_v;
  Real C_i;
  Real C_n_v;
  Real C_p_v;
  Real C_v;
  Real G_p_v;
  Real L_i;
  Real L_n_v;
  Real L_p_v;
  Real L_v;
  Real R1_i;
  Real R1_n_i;
  Real R1_n_v;
  Real R1_p_i;
  Real R1_p_v;
  Real R1_v;
  Real R2_i;
  Real R2_n_v;
  Real R2_p_i;
  Real R2_p_v;
  Real R2_v;
  Real AC_n_i;
  Real AC_p_i;
  Real C_n_i;
  Real C_p_i;
  Real G_p_i;
  Real L_n_i;
  Real L_p_i;
  Real R2_n_i;
  parameter Real AC_A = 1.0;
  parameter Real AC_w = 1.0;
  parameter Real C_C = 0.01;
  parameter Real L_L = 0.1;
  parameter Real R1_R = 10.0;
  parameter Real R2_R = 100.0;
equation
  R2_p_v = AC_p_v;
  R2_p_v = R1_p_v;
  C_p_v = R1_n_v;
  R2_n_v = L_p_v;
  AC_n_v = C_n_v;
  AC_n_v = L_n_v;
  AC_n_v = G_p_v;
  R1_n_i + C_p_i = 0.0;
  L_p_i + R2_n_i = 0.0;
  G_p_i + C_n_i + L_n_i + AC_n_i = 0.0;
  R1_p_i + R2_p_i + AC_p_i = 0.0;
  R1_R * R1_i = R1_v;
  R1_v = R1_p_v - R1_n_v;
  0.0 = R1_p_i + R1_n_i;
  R1_i = R1_p_i;
  C_i = C_C * der(C_v);
  C_v = C_p_v - C_n_v;
  0.0 = C_p_i + C_n_i;
  C_i = C_p_i;
  R2_R * R2_i = R2_v;
  R2_v = R2_p_v - R2_n_v;
  0.0 = R2_p_i + R2_n_i;
  R2_i = R2_p_i;
  L_L * der(L_i) = L_v;
  L_v = L_p_v - L_n_v;
  0.0 = L_p_i + L_n_i;
  L_i = L_p_i;
  AC_v = AC_A * sin(AC_w * time);
  AC_v = AC_p_v - AC_n_v;
  0.0 = AC_p_i + AC_n_i;
  AC_i = AC_p_i;
  G_p_v = 0.0;
end SimpleCircuit;