# Makefile generated by OpenModelica
# Platform: darwin64

# Simulations use -O3 by default
CC=clang
CXX=clang++
LINK=clang -single_module -dynamiclib -flat_namespace
EXEEXT=
DLLEXT=.dylib
CFLAGS_BASED_ON_INIT_FILE=
# define OMC_CFLAGS_OPTIMIZATION env variable to your desired optimization level to override this
OMC_CFLAGS_OPTIMIZATION=-Os
DEBUG_FLAGS=$(OMC_CFLAGS_OPTIMIZATION)
CFLAGS= $(CFLAGS_BASED_ON_INIT_FILE) $(DEBUG_FLAGS) -DOM_HAVE_PTHREADS -fPIC -DOM_HAVE_PTHREADS    
CPPFLAGS= -I"/Users/jtinnerholm/Projects/External/OpenModelica/build_cmake/install_cmake/include/omc/c" -I"/Users/jtinnerholm/Projects/External/OpenModelica/build_cmake/install_cmake/include/omc" -I. -DOPENMODELICA_XML_FROM_FILE_AT_RUNTIME -DOMC_MODEL_PREFIX=LapackExternal_SolveInTime -DOMC_NUM_MIXED_SYSTEMS=0 -DOMC_NUM_LINEAR_SYSTEMS=0 -DOMC_NUM_NONLINEAR_SYSTEMS=0 -DOMC_NDELAY_EXPRESSIONS=0 -DOMC_NVAR_STRING=0
# define OMC_LDFLAGS_LINK_TYPE env variable to "static" to override this
OMC_LDFLAGS_LINK_TYPE=dynamic
RUNTIME_LIBS= -lSimulationRuntimeC -lOpenModelicaRuntimeC -lomcgc -llapack -lblas -lm
LDFLAGS=-L"/Users/jtinnerholm/Projects/External/OpenModelica/build_cmake/install_cmake/lib//omc" -L"/Users/jtinnerholm/Projects/External/OpenModelica/build_cmake/install_cmake/lib" -Wl,-rpath,"/Users/jtinnerholm/Projects/External/OpenModelica/build_cmake/install_cmake/lib//omc"  -Wl,-rpath,"/Users/jtinnerholm/Projects/External/OpenModelica/build_cmake/install_cmake/lib"   $(RUNTIME_LIBS) 
DIREXTRA=-L"/private/tmp/claude-501/-Users-jtinnerholm-Projects-OM-jl/b641726d-b670-4cbc-baca-f2f76a972607/scratchpad/om-bld/test/Models"
MAINFILE=LapackExternal.SolveInTime.c
MAINOBJ=LapackExternal.SolveInTime.o
CFILES=LapackExternal.SolveInTime_functions.c LapackExternal.SolveInTime_records.c \
LapackExternal.SolveInTime_01exo.c LapackExternal.SolveInTime_02nls.c LapackExternal.SolveInTime_03lsy.c LapackExternal.SolveInTime_04set.c LapackExternal.SolveInTime_05evt.c LapackExternal.SolveInTime_06inz.c LapackExternal.SolveInTime_07dly.c \
LapackExternal.SolveInTime_08bnd.c LapackExternal.SolveInTime_09alg.c LapackExternal.SolveInTime_10asr.c LapackExternal.SolveInTime_11mix.c LapackExternal.SolveInTime_12jac.c LapackExternal.SolveInTime_13opt.c LapackExternal.SolveInTime_14lnz.c \
LapackExternal.SolveInTime_15syn.c LapackExternal.SolveInTime_16dae.c LapackExternal.SolveInTime_17inl.c LapackExternal.SolveInTime_18spd.c 

OFILES=$(CFILES:.c=.o)
GENERATEDFILES=$(MAINFILE) LapackExternal.SolveInTime.makefile LapackExternal.SolveInTime_literals.h LapackExternal.SolveInTime_functions.h $(CFILES)

.PHONY: omc_main_target clean bundle

# This is to make sure that LapackExternal.SolveInTime_*.c are always compiled.
.PHONY: $(CFILES)

omc_main_target: $(MAINOBJ) LapackExternal.SolveInTime_functions.h LapackExternal.SolveInTime_literals.h $(OFILES)
	$(CC) -I. -o LapackExternal.SolveInTime$(EXEEXT) $(MAINOBJ) $(OFILES) $(DIREXTRA)   $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)

omc_dll_target: $(MAINOBJ) LapackExternal.SolveInTime_functions.h LapackExternal.SolveInTime_literals.h $(OFILES)
	$(CC) -DOMC_DLL_MAIN_DEFINE -o $(MAINOBJ) -c $(MAINFILE) $(DIREXTRA)   $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)
	$(CC) -shared -I. -o LapackExternal.SolveInTime$(DLLEXT) $(MAINOBJ) $(OFILES) $(DIREXTRA)   $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)

clean:
	@rm -f LapackExternal.SolveInTime_records.o $(MAINOBJ)

bundle:
	@tar -cvf LapackExternal.SolveInTime_Files.tar $(GENERATEDFILES)