/* Additional record code for LapackExternal.SolveInTime generated by the OpenModelica Compiler v1.27.1-cmake. */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "LapackExternal.SolveInTime_functions.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

