/* Simulation code for LapackExternal.SolveInTime generated by the OpenModelica Compiler v1.27.1-cmake. */
#if !defined(LapackExternal_SolveInTime__MODEL_H)
#define LapackExternal_SolveInTime__MODEL_H

#if defined(__cplusplus)
extern "C" {
#endif

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "simulation/jacobian_util.h"
#include "simulation/simulation_omc_assert.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"
#include "simulation/solver/spatialDistribution.h"
#include "simulation/solver/synchronous.h"

#include <string.h>

#include "LapackExternal.SolveInTime_functions.h"

#define Modelica_Math_Matrices_solve_index 0
#define Modelica_Math_Matrices_LAPACK_dgesv__vec_index 1

extern void LapackExternal_SolveInTime_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void LapackExternal_SolveInTime_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int LapackExternal_SolveInTime_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int LapackExternal_SolveInTime_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int LapackExternal_SolveInTime_function_storeSpatialDistribution(DATA *data, threadData_t *threadData);
extern int LapackExternal_SolveInTime_function_initSpatialDistribution(DATA *data, threadData_t *threadData);
extern int LapackExternal_SolveInTime_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int LapackExternal_SolveInTime_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int LapackExternal_SolveInTime_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int LapackExternal_SolveInTime_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int LapackExternal_SolveInTime_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int LapackExternal_SolveInTime_checkForAsserts(DATA *data, threadData_t *threadData);
extern int LapackExternal_SolveInTime_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int LapackExternal_SolveInTime_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int LapackExternal_SolveInTime_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* LapackExternal_SolveInTime_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* LapackExternal_SolveInTime_relationDescription(int i);
extern void LapackExternal_SolveInTime_function_initSample(DATA *data, threadData_t *threadData);
extern int LapackExternal_SolveInTime_initialAnalyticJacobianG(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int LapackExternal_SolveInTime_initialAnalyticJacobianA(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int LapackExternal_SolveInTime_initialAnalyticJacobianADJ(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int LapackExternal_SolveInTime_initialAnalyticJacobianB(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int LapackExternal_SolveInTime_initialAnalyticJacobianC(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int LapackExternal_SolveInTime_initialAnalyticJacobianD(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int LapackExternal_SolveInTime_initialAnalyticJacobianF(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int LapackExternal_SolveInTime_initialAnalyticJacobianH(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int LapackExternal_SolveInTime_functionJacG_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int LapackExternal_SolveInTime_functionJacA_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int LapackExternal_SolveInTime_functionJacADJ_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int LapackExternal_SolveInTime_functionJacB_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int LapackExternal_SolveInTime_functionJacC_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int LapackExternal_SolveInTime_functionJacD_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int LapackExternal_SolveInTime_functionJacF_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int LapackExternal_SolveInTime_functionJacH_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern const char* LapackExternal_SolveInTime_linear_model_frame(void);
extern const char* LapackExternal_SolveInTime_linear_model_datarecovery_frame(void);
extern int LapackExternal_SolveInTime_mayer(DATA* data, modelica_real** res, short *);
extern int LapackExternal_SolveInTime_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int LapackExternal_SolveInTime_getInputVarIndicesInOptimization(DATA* data, int* input_var_indices);
extern int LapackExternal_SolveInTime_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int LapackExternal_SolveInTime_setInputData(DATA *data, const modelica_boolean file);
extern int LapackExternal_SolveInTime_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void LapackExternal_SolveInTime_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void LapackExternal_SolveInTime_function_updateSynchronous(DATA * data, threadData_t *threadData, long base_idx);
extern int LapackExternal_SolveInTime_function_equationsSynchronous(DATA * data, threadData_t *threadData, long base_idx, long sub_idx);
extern void LapackExternal_SolveInTime_read_simulation_info(SIMULATION_INFO* simulationData);
extern void LapackExternal_SolveInTime_read_input_fmu(MODEL_DATA* modelData);
extern void LapackExternal_SolveInTime_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int LapackExternal_SolveInTime_inputNames(DATA* data, char ** names);
extern int LapackExternal_SolveInTime_dataReconciliationInputNames(DATA* data, char ** names);
extern int LapackExternal_SolveInTime_dataReconciliationUnmeasuredVariables(DATA* data, char ** names);
extern int LapackExternal_SolveInTime_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int LapackExternal_SolveInTime_functionLocalKnownVars(DATA* data, threadData_t* threadData);
extern int LapackExternal_SolveInTime_symbolicInlineSystem(DATA* data, threadData_t* threadData);

#include "LapackExternal.SolveInTime_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(LapackExternal_SolveInTime__MODEL_H) */


