# Curated from `--trace-compile` runs over `OM.simulate("HelloWorld", ...)`
# and `OM.simulate("EventTests.WhenAssignment", ...)`. Keep this file to
# stable package-owned signatures; generated model modules and compiler
# internals are intentionally excluded.

precompile(Tuple{typeof(Core.kwcall), NamedTuple{(:startTime, :stopTime, :overwriteCache), Tuple{Float64, Float64, Bool}}, typeof(simulate), String, String})
precompile(Tuple{typeof(Core.kwcall), NamedTuple{(:functionList, :BackendMode, :warnMissingStartValues, :eliminateNonDynamic, :observedFilter, :checkSimCode), Tuple{ImmutableList.ListDef.Nil{Any}, OMBackend.BackendMode, Nothing, Bool, Nothing, Bool}}, typeof(OMBackend.translate), Union{DAE.DAE_LIST, OMFrontend.Frontend.NFFlatModel}})

precompile(Tuple{typeof(OMFrontend.cacheToFunctionList), OMFrontend.Frontend.FunctionTreeImpl.EMPTY})
precompile(Tuple{typeof(OMFrontend.Frontend.AbsynToSCode.translateEquation), Absyn.EQ_IF, SCode.COMMENT, MetaModelica.SOURCEINFO, Bool})
precompile(Tuple{typeof(OMFrontend.Frontend.AbsynToSCode.translateEquation), Absyn.EQ_NORETCALL, SCode.COMMENT, MetaModelica.SOURCEINFO, Bool})
precompile(Tuple{typeof(OMFrontend.Frontend.AbsynToSCode.translateEquation), Absyn.EQ_WHEN_E, SCode.COMMENT, MetaModelica.SOURCEINFO, Bool})
precompile(Tuple{typeof(OMFrontend.Frontend.convertEquation), OMFrontend.Frontend.EQUATION_EQUALITY, ImmutableList.ListDef.Nil{Any}})
precompile(Tuple{typeof(OMFrontend.Frontend.convertEquation), OMFrontend.Frontend.EQUATION_WHEN{DAE.SOURCE}, ImmutableList.ListDef.Cons{DAE.Element}})
precompile(Tuple{typeof(OMFrontend.Frontend.convertEquations), Array{OMFrontend.Frontend.NFEquation, 1}})
precompile(Tuple{typeof(OMFrontend.Frontend.map), OMFrontend.Frontend.NFEquation, typeof(OMBackend.FrontendUtil.removeSmooth)})
precompile(Tuple{typeof(OMBackend.FrontendUtil.removeSmooth), OMFrontend.Frontend.EQUATION_EQUALITY})
precompile(Tuple{typeof(OMBackend.FrontendUtil.removeSmooth), OMFrontend.Frontend.EQUATION_WHEN{DAE.SOURCE}})

precompile(Tuple{typeof(OMBackend.Backend.BDAECreate.createWhenOperators), ImmutableList.ListDef.Cons{DAE.Element}, ImmutableList.ListDef.Nil{Any}})
precompile(Tuple{typeof(OMBackend.Backend.BDAECreate.createWhenOperators), ImmutableList.ListDef.Nil{Any}, ImmutableList.ListDef.Cons{OMBackend.Backend.BDAE.WhenOperator}})
precompile(Tuple{typeof(OMBackend.Backend.BDAECreate.structuralHash), Bool, UInt64})
precompile(Tuple{typeof(OMBackend.Backend.BDAECreate.structuralHash), Float64, UInt64})
precompile(Tuple{typeof(OMBackend.Backend.BDAECreate.structuralHash), ImmutableList.ListDef.Cons{DAE.Exp}, UInt64})
precompile(Tuple{typeof(OMBackend.Backend.BDAECreate.structuralHash), ImmutableList.ListDef.Cons{OMBackend.Backend.BDAE.WhenOperator}, UInt64})
precompile(Tuple{typeof(OMBackend.Backend.BDAECreate.structuralHash), ImmutableList.ListDef.Cons{SCode.Comment}, UInt64})
precompile(Tuple{typeof(OMBackend.Backend.BDAECreate.structuralHash), ImmutableList.ListDef.Nil{Any}, UInt64})
precompile(Tuple{typeof(OMBackend.Backend.BDAECreate.structuralHash), Int64, UInt64})
precompile(Tuple{typeof(OMBackend.Backend.BDAECreate.structuralHash), Nothing, UInt64})
precompile(Tuple{typeof(OMBackend.Backend.BDAECreate.structuralHash), String, UInt64})
precompile(Tuple{typeof(OMBackend.Backend.BDAECreate.synthesizeFromInitialAlgorithms), Array{OMFrontend.Frontend.NFAlgorithm, 1}})
precompile(Tuple{typeof(OMBackend.Backend.BDAECreate.synthesizeInitialWhenFromAlgorithms), Array{OMFrontend.Frontend.NFAlgorithm, 1}})

precompile(Tuple{typeof(OMBackend.Backend.Causalize.detectStateExpression), DAE.BINARY, Base.Dict{DAE.ComponentRef, Bool}})
precompile(Tuple{typeof(OMBackend.Backend.Causalize.detectStateExpression), DAE.CALL, Base.Dict{DAE.ComponentRef, Bool}})
precompile(Tuple{typeof(OMBackend.Backend.Causalize.detectStateExpression), DAE.CREF, Base.Dict{DAE.ComponentRef, Bool}})
precompile(Tuple{typeof(OMBackend.Backend.Causalize.detectStateExpression), DAE.RCONST, Base.Dict{DAE.ComponentRef, Bool}})
precompile(Tuple{typeof(OMBackend.Backend.Causalize.detectStateExpression), DAE.RELATION, Base.Dict{DAE.ComponentRef, Bool}})
precompile(Tuple{typeof(OMBackend.Backend.Causalize.detectStateExpression), DAE.UNARY, Base.Dict{DAE.ComponentRef, Bool}})
precompile(Tuple{typeof(OMBackend.Backend.Causalize.hasFinalArrayWithSubscripts), DAE.CREF_IDENT})
precompile(Tuple{typeof(OMBackend.Backend.Causalize.transformASUBInDer), DAE.BINARY, Nothing})
precompile(Tuple{typeof(OMBackend.Backend.Causalize.transformASUBInDer), DAE.CALL, Nothing})
precompile(Tuple{typeof(OMBackend.Backend.Causalize.transformASUBInDer), DAE.CREF, Nothing})
precompile(Tuple{typeof(OMBackend.Backend.Causalize.transformASUBInDer), DAE.RCONST, Nothing})
precompile(Tuple{typeof(OMBackend.Backend.Causalize.transformASUBInDer), DAE.RELATION, Nothing})
precompile(Tuple{typeof(OMBackend.Backend.Causalize.transformASUBInDer), DAE.UNARY, Nothing})

precompile(Tuple{typeof(OMBackend.Backend.BDAEUtil.detectStateExpression), DAE.BINARY, Base.Dict{DAE.ComponentRef, Bool}})
precompile(Tuple{typeof(OMBackend.Backend.BDAEUtil.detectStateExpression), DAE.CALL, Base.Dict{DAE.ComponentRef, Bool}})
precompile(Tuple{typeof(OMBackend.Backend.BDAEUtil.detectStateExpression), DAE.CREF, Base.Dict{DAE.ComponentRef, Bool}})
precompile(Tuple{typeof(OMBackend.Backend.BDAEUtil.detectStateExpression), DAE.RCONST, Base.Dict{DAE.ComponentRef, Bool}})
precompile(Tuple{typeof(OMBackend.Backend.BDAEUtil.detectStateExpression), DAE.UNARY, Base.Dict{DAE.ComponentRef, Bool}})
precompile(Tuple{typeof(OMBackend.Backend.BDAEUtil.getAllVariables), OMBackend.Backend.BDAE.ASSIGN, Array{OMBackend.Backend.BDAE.VAR, 1}})
precompile(Tuple{typeof(OMBackend.Backend.BDAEUtil.traverseWhenEquation!), OMBackend.Backend.BDAE.WHEN_STMTS, Function, Base.Dict{DAE.ComponentRef, Bool}})
precompile(Tuple{typeof(OMBackend.Backend.BDAEUtil.traverseWhenEquation!), OMBackend.Backend.BDAE.WHEN_STMTS, Function, Nothing})
precompile(Tuple{typeof(OMBackend.Backend.BackendEquation.makeResidualEquation), OMBackend.Backend.BDAE.EQUATION})
precompile(Tuple{typeof(OMBackend.Backend.BackendEquation.makeResidualEquation), OMBackend.Backend.BDAE.WHEN_EQUATION})

precompile(Tuple{typeof(OMBackend.FrontendUtil.Util.getAllCrefs), DAE.BINARY})
precompile(Tuple{typeof(OMBackend.FrontendUtil.Util.getAllCrefs), DAE.CREF})
precompile(Tuple{typeof(OMBackend.FrontendUtil.Util.getAllCrefs2), DAE.BINARY, ImmutableList.ListDef.Cons{DAE.ComponentRef}})
precompile(Tuple{typeof(OMBackend.FrontendUtil.Util.getAllCrefs2), DAE.BINARY, ImmutableList.ListDef.Nil{Any}})
precompile(Tuple{typeof(OMBackend.FrontendUtil.Util.getAllCrefs2), DAE.CALL, ImmutableList.ListDef.Nil{Any}})
precompile(Tuple{typeof(OMBackend.FrontendUtil.Util.getAllCrefs2), DAE.CREF, ImmutableList.ListDef.Cons{DAE.ComponentRef}})
precompile(Tuple{typeof(OMBackend.FrontendUtil.Util.getAllCrefs2), DAE.CREF, ImmutableList.ListDef.Nil{Any}})
precompile(Tuple{typeof(OMBackend.FrontendUtil.Util.getAllCrefs2), DAE.RCONST, ImmutableList.ListDef.Cons{DAE.ComponentRef}})
precompile(Tuple{typeof(OMBackend.FrontendUtil.Util.getAllCrefs2), DAE.RCONST, ImmutableList.ListDef.Nil{Any}})
precompile(Tuple{typeof(OMBackend.FrontendUtil.Util.getAllCrefs2), DAE.RELATION, ImmutableList.ListDef.Nil{Any}})
precompile(Tuple{typeof(OMBackend.FrontendUtil.Util.getAllCrefs2), DAE.UNARY, ImmutableList.ListDef.Cons{DAE.ComponentRef}})
precompile(Tuple{typeof(OMBackend.FrontendUtil.Util.traverseExpTopDown), DAE.Exp, typeof(OMBackend.Backend.BDAEUtil.detectStateExpression), Base.Dict{DAE.ComponentRef, Bool}})
precompile(Tuple{typeof(OMBackend.FrontendUtil.Util.traverseExpTopDown), DAE.Exp, typeof(OMBackend.Backend.Causalize.detectStateExpression), Base.Dict{DAE.ComponentRef, Bool}})
precompile(Tuple{typeof(OMBackend.FrontendUtil.Util.traverseExpTopDown), DAE.Exp, typeof(OMBackend.Backend.Causalize.transformASUBInDer), Nothing})
precompile(Tuple{typeof(OMBackend.FrontendUtil.Util.traverseExpTopDown), DAE.Exp, typeof(OMBackend.FrontendUtil.Util.getAllCrefs2), ImmutableList.ListDef.Cons{DAE.ComponentRef}})
precompile(Tuple{typeof(OMBackend.FrontendUtil.Util.traverseExpTopDown), DAE.Exp, typeof(OMBackend.FrontendUtil.Util.getAllCrefs2), ImmutableList.ListDef.Nil{Any}})

precompile(Tuple{typeof(OMBackend.SimulationCode.toSimExp), DAE.BINARY})
precompile(Tuple{typeof(OMBackend.SimulationCode.toSimExp), DAE.CALL})
precompile(Tuple{typeof(OMBackend.SimulationCode.toSimExp), DAE.CREF})
precompile(Tuple{typeof(OMBackend.SimulationCode.toSimExp), DAE.RCONST})
precompile(Tuple{typeof(OMBackend.SimulationCode.toSimExp), DAE.RELATION})
precompile(Tuple{typeof(OMBackend.SimulationCode.toSimExp), DAE.UNARY})
precompile(Tuple{typeof(OMBackend.SimulationCode.toSimExp), OMBackend.SimulationCode.Exp})
precompile(Tuple{typeof(OMBackend.SimulationCode.toDAEExp), OMBackend.SimulationCode.BINARY})
precompile(Tuple{typeof(OMBackend.SimulationCode.toDAEExp), OMBackend.SimulationCode.CALL})
precompile(Tuple{typeof(OMBackend.SimulationCode.toDAEExp), OMBackend.SimulationCode.RCONST})
precompile(Tuple{typeof(OMBackend.SimulationCode.toDAEExp), OMBackend.SimulationCode.RELATION})
precompile(Tuple{typeof(OMBackend.SimulationCode.toDAEExp), OMBackend.SimulationCode.UNARY})
precompile(Tuple{typeof(OMBackend.SimulationCode.DAE_identifierToString), DAE.CREF_IDENT})
precompile(Tuple{typeof(OMBackend.SimulationCode.expandRecordArgsInExp), DAE.BINARY})
precompile(Tuple{typeof(OMBackend.SimulationCode.expandRecordArgsInExp), DAE.CALL})
precompile(Tuple{typeof(OMBackend.SimulationCode.expandRecordArgsInExp), DAE.CREF})
precompile(Tuple{typeof(OMBackend.SimulationCode.expandRecordArgsInExp), DAE.RCONST})
precompile(Tuple{typeof(OMBackend.SimulationCode.expandRecordArgsInExp), DAE.UNARY})

precompile(Tuple{typeof(OMBackend.SimulationCode._canonicalizeComponentRef), DAE.CREF_IDENT, DAE.T_REAL, OMBackend.SimulationCode._CanonicalNameContext})
precompile(Tuple{typeof(OMBackend.SimulationCode._canonicalizeCrefExpSIM), Any, OMBackend.SimulationCode._CanonicalNameContext})
precompile(Tuple{typeof(OMBackend.SimulationCode._canonicalizeExp), Any, OMBackend.SimulationCode._CanonicalNameContext})
precompile(Tuple{typeof(OMBackend.SimulationCode._canonicalizeExp), OMBackend.SimulationCode.BINARY, OMBackend.SimulationCode._CanonicalNameContext})
precompile(Tuple{typeof(OMBackend.SimulationCode._canonicalizeExp), OMBackend.SimulationCode.EXP_CREF, OMBackend.SimulationCode._CanonicalNameContext})
precompile(Tuple{typeof(OMBackend.SimulationCode._canonicalizeExp), OMBackend.SimulationCode.RCONST, OMBackend.SimulationCode._CanonicalNameContext})
precompile(Tuple{typeof(OMBackend.SimulationCode._canonicalizeWhenOperator), OMBackend.SimulationCode.ASSIGN, OMBackend.SimulationCode._CanonicalNameContext})

precompile(Tuple{typeof(OMBackend.CodeGeneration.AlgorithmicCodeGeneration._unwrapSubscriptExpr), Symbol})
precompile(Tuple{typeof(OMBackend.CodeGeneration.CodeGenerationUtil._asDAE), OMBackend.SimulationCode.BINARY})
precompile(Tuple{typeof(OMBackend.CodeGeneration.CodeGenerationUtil._asDAE), OMBackend.SimulationCode.EXP_CREF})
precompile(Tuple{typeof(OMBackend.CodeGeneration.CodeGenerationUtil.collectCalledFunctionNames!), Base.Set{String}, DAE.Exp})
precompile(Tuple{typeof(OMBackend.CodeGeneration.CodeGenerationUtil.collectCalledFunctionNames!), Base.Set{String}, OMBackend.SimulationCode.ASSIGN})
precompile(Tuple{typeof(OMBackend.CodeGeneration._exprToRTGFunction), Expr})
precompile(Tuple{typeof(OMBackend.CodeGeneration._isSimpleLeafExpr), Expr})
precompile(Tuple{typeof(OMBackend.CodeGeneration._isZeroLiteral), Int64})
precompile(Tuple{typeof(OMBackend.CodeGeneration.substituteDer), Expr, Symbol, Int64})

precompile(Tuple{typeof(OMBackend.canonicalName), Absyn.IDENT})
precompile(Tuple{typeof(OMBackend.canonicalName), DAE.CREF_IDENT})
precompile(Tuple{typeof(OMBackend._subscriptSuffix), ImmutableList.ListDef.Nil{Any}})
precompile(Tuple{typeof(OMBackend.logRunModelName), OMFrontend.Frontend.FLAT_MODEL})
precompile(Tuple{typeof(MetaModelica.referenceEq), ImmutableList.ListDef.Nil{Any}, ImmutableList.ListDef.Nil{Any}})
